version: "3.9"

services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - elastic
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/store
      - ELASTICSEARCH_HOST=http://elastic:9200
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: store
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    mem_limit: 1g

volumes:
  pgdata:
  esdata:
